apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-service
spec:
  selector:
    app: spring-test-app
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8080
  type: LoadBalance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-test-app
spec:
  selector:
    matchLabels:
      app: spring-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-test-app
    spec:
      containers:
        - name: spring-test-app
          image: babani/spring-kubernetes # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
